"""Remove has_voted field from User model

Revision ID: 5ee30cbea213
Revises: bdc193ae9584
Create Date: 2024-05-25 16:35:56.720096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ee30cbea213'
down_revision = 'bdc193ae9584'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('has_voted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_voted', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
